version: "3"
services:
  grafana:
    image: grafana/grafana-oss:8.2.6
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_ALLOW_LOADING_UNSIGNED_PLUGINS=lightstep-metrics-datasource
      - GF_LOG_LEVEL=debug
      - GF_DEFAULT_APP_MODE=development
    volumes:
      - grafana-data-lmd:/var/lib/grafana
      - ./dist:/var/lib/grafana/plugins/lightstep-metrics-datasource
volumes:
  grafana-data-lmd:
    external: true